import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import type { ReactNode } from "react";
import { getLocale } from "next-intl/server";
import { LocaleSwitcher } from "@/components/locale-switcher";
import { GlobalProviders } from "@/app/providers/global-providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-dvh flex-col`}
      >
        <GlobalProviders>
          <LocaleSwitcher />

          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
